"""empty message

Revision ID: 83b62f7e1b2e
Revises: 98482dbd6732
Create Date: 2024-04-24 15:47:15.744298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b62f7e1b2e'
down_revision = '98482dbd6732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_release', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('date_of_release')

    # ### end Alembic commands ###
